version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080 # replace with OpenFaaS gateway address
functions:
  Split:
    lang: python3-flask
    handler: ../functions/Split    
    image: ahborhani/split

  countBatchPatternOcs:
    lang: python3-flask
    handler: ../functions/Count  
    image: ahborhani/count

  addUpOcs:
    lang: python3-flask
    handler: ../functions/Sum   
    image: ahborhani/sum


  
